version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: src/Gateway.API/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      - ServiceConfiguration__LaravelApi=http://laravel-api:8000
      - ServiceConfiguration__RecommendationService=http://recommendation-service:5000
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
